name: Chess.com Games & Stats

on:
  schedule:
    - cron: '*/5 * * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    name: Update readme with your chess stats and games
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Balastrong/chess-stats-action@v2.0.1
        with:
          CHESS_USERNAME: 'TortellinoAmoreMio'
